/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.11.0
 *
 * Project: 'C542RC_AudioLoopback.debug_GCC+NUCLEO-C542RC' 
 * Target:  'debug_GCC+NUCLEO-C542RC' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* STMicroelectronics::Device:STM32CubeMX2 Config:RCC@2.1.0 */
#define USE_EXTERNAL_ENV
/* STMicroelectronics::USB:STM32CubeMX2 Codegen:Device_Core@2.1.0 */
#define USBD_INCLUDE_USER_DESC_CONFIG_FILE
/* STMicroelectronics::USB:STM32CubeMX2 Config:USBX@2.1.0 */
#define UX_INCLUDE_USER_DEFINE_FILE


#endif /* PRE_INCLUDE_GLOBAL_H */
